artifacts_root: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-data.zip  # Add this line
  local_data_file: C:\Users\layek\Downloads\wine+quality.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts\data_ingestion\winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

